# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4c4f0ed03ebd55ce7d2888a1e9b03344b0bc58540125bd0599ea18b56b70b167d03a5bc20a4c7a86f4cf61a199e41bdc9747afd65d0bb726852d0330420b211

test:
  secret_key_base: b224f877524aa9c77a2cb2ff0f4a96d513c289b837ad54480e365df0343111571417659380cdac0568b6328f1a4dc6ab9df466b800224c713d54b4a87590caf5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
