# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LoginReg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joining_user', models.ManyToManyField(related_name='joiningtrip', to='LoginReg.User')),
                ('planned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannertrip', to='LoginReg.User')),
            ],
        ),
    ]
