# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LoginReg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_of_quote', models.CharField(max_length=255)),
                ('quote_content', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logged_in_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_user', to='LoginReg.User')),
            ],
        ),
        migrations.AddField(
            model_name='favorites',
            name='fquote_q',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fquot_q', to='Quotes.Quotes'),
        ),
        migrations.AddField(
            model_name='favorites',
            name='user_fav_quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_fav_quote', to='LoginReg.User'),
        ),
    ]
