# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 757280aa644a2b7e4602a845ea3b313a1e28c5844f468cfde78d36da543066645c0435a4d9fa97b46f8b6b207411fcf55c0b1e755c253a2c82fc6e833133c982

test:
  secret_key_base: daa1f7cec2a35e12fa4f9b6da6eb8bb6a9bb530268260f5041487ab9f862a880e27cd3843791b59870d173b7a1197a169d0e3ca62466776a717836dfef23f332

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
