# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BeltReviewApps', '0001_initial'),
        ('BookApps', '0002_auto_20170331_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='book_reviews', to='BookApps.Books'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posted_reviews', to='BeltReviewApps.User'),
            preserve_default=False,
        ),
    ]
