# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LoginReg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_by', models.CharField(max_length=255)),
                ('quote_message', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_user', to='LoginReg.User')),
            ],
        ),
        migrations.AddField(
            model_name='favorites',
            name='quotes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quot', to='Quotes.Quotes'),
        ),
        migrations.AddField(
            model_name='favorites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav', to='LoginReg.User'),
        ),
    ]
