# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='interests',
            name='interestFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_FK', to='Interests.Users'),
        ),
        migrations.AddField(
            model_name='interests',
            name='nameFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_FK', to='Interests.Users'),
        ),
    ]
