# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Interests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interests',
            name='interestFK',
        ),
        migrations.RemoveField(
            model_name='interests',
            name='nameFK',
        ),
        migrations.AddField(
            model_name='users',
            name='interest',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='Interests.Interests'),
            preserve_default=False,
        ),
    ]
