# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TravelBuddyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('travelStart', models.DateField(blank=True, null=True, verbose_name='date')),
                ('travelEnd', models.DateField(blank=True, null=True, verbose_name='date')),
                ('description', models.TextField(max_length=500)),
                ('user', models.ManyToManyField(related_name='trips', to='TravelBuddyApp.User')),
            ],
        ),
    ]
