# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MultAppsApp', '0001_initial'),
        ('CoursesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_courses', to='CoursesApp.Courses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_users', to='MultAppsApp.User')),
            ],
        ),
    ]
