# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LoginReg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('departure', models.DateField()),
                ('arrival', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('userjoining', models.ManyToManyField(related_name='user_joining', to='LoginReg.User')),
                ('userplanning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_planning', to='LoginReg.User')),
            ],
        ),
    ]
