# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8715f076402f74765fd6dfe9d1dde2118aef809520fe617ff3814cad09771a5d6973c28369dbef1eb48e6d055ce0790ddd319c8280f43e26a887da3fcf95a722

test:
  secret_key_base: b410983b59d842de66fc7f679cb14945efef09b51a1c9e3c3cfb984b820612072c65f03dc054e39826730a03a7e0e3bb793a741e612386b7539a10e0389a889b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
