# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Interest', '0002_auto_20170503_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interestFK', to='Interest.Interests')),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='userInterest',
        ),
        migrations.AddField(
            model_name='usersinterest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userFK', to='Interest.Users'),
        ),
    ]
