# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da04295b40e672552ca3c93635e5830ecb6111fb00eeb64920df4db129b0b3c387c81ecadcbbe23d4c7ed2a9196f2e4002bdf99a3f9607dfabb334798596bbd3

test:
  secret_key_base: 5f73d9dade9cd0bb61ca7719483160fbf0e628893e100f4d54af486cb36321a454a1ea52159c13f47525e9599b915d19025b7e2a801b123c01874abc9550d41c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
