# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 671668d769cfe8c758a2feae0d76cba6bc4c3ed22634e6873bb20f97b0c374c54b78b70f6058ab845105912c0a0a4bba3ccc020419677cc77c2a9942843cf1e2

test:
  secret_key_base: f54bf52d8f3f5a15da100362c884200294a766c455c315a64a4eb7d4831bbcd90ebba2a4261d3d6b1c1411a345845ce4a59b91afc20e1e4934df7604f2c3dc06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
