# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TravelBuddyApp', '0001_initial'),
        ('TravelPlansApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='user',
        ),
        migrations.AddField(
            model_name='trips',
            name='joining_user',
            field=models.ManyToManyField(related_name='joiningtrip', to='TravelBuddyApp.User'),
        ),
        migrations.AddField(
            model_name='trips',
            name='planned_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plannertrip', to='TravelBuddyApp.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trips',
            name='travelEnd',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trips',
            name='travelStart',
            field=models.DateField(),
        ),
    ]
